In [3]:
path = r"C:\Users\aksel\Downloads\.ethograph\alignment.nwb"

from pynwb import NWBHDF5IO

nwbfile = NWBHDF5IO(path, "r").read()

In [4]:
nwbfile

root pynwb.file.NWBFile at 0x2069342674560
Fields:
  acquisition: {
    pose_cam-1 <class 'pynwb.image.ImageSeries'>,
    video_cam-1 <class 'pynwb.image.ImageSeries'>
  }
  devices: {
    cam-1 <class 'pynwb.device.Device'>
  }
  file_create_date: [datetime.datetime(2026, 5, 15, 13, 55, 27, 506749, tzinfo=tzoffset(None, 7200))]
  identifier: 274cdc75-d7fd-40b6-8ffe-209531b9d331
  intervals: {
    trials <class 'pynwb.epoch.TimeIntervals'>
  }
  session_description: NWB file for media alignment (ethograph generated).
  session_start_time: 2026-05-15 13:55:27.506749+02:00
  timestamps_reference_time: 2026-05-15 13:55:27.506749+02:00
  trials: trials <class 'pynwb.epoch.TimeIntervals'>